language: ruby
rvm:
 - ruby-2.6.1
sudo: false
notifications:
  email: false
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:schema:load db:seed --trace
cache: bundler
services:
  - postgresql
addons:
  postgresql: 9.4
