default: &default
  database: legalerts_<%= Rails.env %>
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  username: postgres

production:
  <<: *default
  database: legalerts
