# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94bf5c532bdc14a00259bb6fa88bb6252b510c61ae43bd404205e403851d36ae4e31072d1c1a90da236d9d63ef410e700259e087b0b002fdd38ff2ecdbd9a9d6

test:
  secret_key_base: 361125611371035c4b02b562004d368c0333c41295a15f3feeafd401806bbd35ed4fcaa941815134bca9b3acfa88952be436e5827e8bbd709218aa9e9398a55b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
